arquivo = open("lorem.txt", "w")
arquivo.write("O comando que você usou em Python abre um arquivo chamado lorem.txt no modo de escrita.\n")
arquivo.close() 
arquivo = open("lorem.txt", "r")
print(arquivo.read())  
arquivo.close() 
arquivo = open("lorem.txt", "a")
arquivo.write("Olá, Mundo")
arquivo.close()
arquivo = open("lorem.txt", "r")
print(arquivo.read())  
arquivo.close() 